spring.application.name=sandbox
spring.datasource.url=jdbc:postgresql://ep-gentle-fog-acda4g78-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_i5Yq1njzbkxV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#si te expongo toda la db cual problema hay